<a href="https://colab.research.google.com/github/Subhasree5/ESSENTIALS-OF-ML-NPTEL-/blob/main/BASICS_OF_MATRIX_ALGEBRA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
p=np.array([[1,7],[2,1],[3,2]])
print(p)

[[1 7]
 [2 1]
 [3 2]]


In [3]:
q=np.array([[1,1],[1,-1]])
print(q)

[[ 1  1]
 [ 1 -1]]


# **MATRIX ADDITION**

In [4]:
c1=np.add(p,q)
print(c1)

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [5]:
r=np.array([[1,1],[1,-1],[1,0]])
print(r)

[[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [6]:
c2=np.add(p,r)
print(c2)

[[2 8]
 [3 0]
 [4 2]]


# **MATRIX SUBTRACTION**

In [7]:
c3=np.subtract(p,r)
print(c3)

[[0 6]
 [1 2]
 [2 2]]


# **MATRIX MULTIPLICATION**

In [8]:
c4=np.dot(p,r)
print(c4)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [9]:
c5=np.dot(p,q)
print(c5)

[[ 8 -6]
 [ 3  1]
 [ 5  1]]


# **DETERMINANT**

In [11]:
detq=np.linalg.det(q)
print(detq)

-2.0


# **INVERSE**

In [12]:
inv=np.linalg.inv(q)
print(inv)

[[ 0.5  0.5]
 [ 0.5 -0.5]]


# **TRANSPOSE**

In [13]:
tra=np.transpose(q)
print(tra)

[[ 1  1]
 [ 1 -1]]
