<a href="https://colab.research.google.com/github/Subhasree5/ESSENTIALS-OF-ML-NPTEL-/blob/main/VECTORS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
v=np.array([1,-1,2])
w=np.array([2,5,2])

# **ADDITION**

In [2]:
print(v+w)

[3 4 4]


# **SUBTRACTION**

In [3]:
print(v-w)

[-1 -6  0]


# **SCALAR MULTIPLICATION**

In [4]:
print(3*v)
print(2*w)

[ 3 -3  6]
[ 4 10  4]


# **LENGTH**

In [5]:
print(np.linalg.norm(v))
print(np.linalg.norm(w))

2.449489742783178
5.744562646538029


# **DOT PRODUCT**

In [6]:
s=np.dot(v,w)
print(s)

1
